# Generated by Django 5.0 on 2024-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('context', models.TextField()),
                ('source', models.TextField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
